apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- mariadb/sealedsecret.yml
patches:
images:
- name: linuxserver/mariadb
  newName: linuxserver/mariadb
  newTag: 10.6.10
- name: vaultwarden/server
  newName: vaultwarden/server
  newTag: 1.27.0-alpine
  