kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
